CORVOID(1)
==========
:doctype: manpage

NAME
----
corvoid - build Java projects

SYNOPSIS
--------
*corvoid* <command>

DESCRIPTION
-----------

Corvoid is a small build tool for Java projects. It implements a limited but
useful subset of the Apache Maven POM format.  It can resolve and download
dependencies then compile and package a project into jar or uberjar file.

Corvoid will never have support for Maven plugins nor the full POM format.

COMMANDS
--------

*corvoid classpath*::
    List the path of all the jar files the project is dependent on in the
    format java's -classpath option expects.

*corvoid compile*::
    Compile the project's source code into class files.

*corvoid deps*::
    Resolve and download the projects dependencies to the local repository
    (~/.m2/repository)

*corvoid jar*::
    Package the project's compiled classes and resources as a jar file.

*corvoid lint*::
    Check the project's dependencies for duplicate classes.

*corvoid new <dir>*::
    Create a new project initialized with the default template.

*corvoid run <class> [arguments...]*::
    Execute the 'main()' method of a class.

*corvoid tree*::
    Display the project's dependencies as a tree.

*corvoid uberjar*::
    Build a standalone executable jar file bundling the project's dependencies.

*corvoid watch*::
    Watch the project's source code for modifications and recompile it when
    changes are saved.

SEE ALSO
--------
mvn(1)